config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resources :boards do
    resources :stuffs
  end

  resources :stuffs do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :stuffs, dependent: :destroy

  def self.all_boards
    Board.find_by_sql(
    "SELECT *
    FROM boards
    ORDER BY boards.name"
    )
  end
end

app/models/stuff.rb
class Stuff < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  before_save :check_author
  belongs_to :stuff

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all_boards
  end

  def show
  end

  def new 
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
  end

  def update 
    if @board.update(board_params)
      redirect_to boards_path
    else 
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  before_action :set_board
  before_action :set_stuff, only: [:show, :edit, :update, :destroy]

  def index
    @stuffs = @board.stuffs
  end

  def show
  end

  def new
    @stuff = @board.stuffs.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @stuff = @board.stuffs.new(stuff_params)

    if @stuff.save
      redirect_to [@board, @stuff]
    else
      render :new
    end
  end

  def update
    if @stuff.update(stuff_params)
      redirect_to [@board, @stuff]
    else
      render :edit
    end
  end

  def destroy
    @stuff.destroy
    redirect_to board_stuffs_path(@board)
  end

  private
    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_stuff
      @stuff = Stuff.find(params[:id])
    end

    def stuff_params
      params.require(:stuff).permit(:name, :body)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_stuff

  def index
    @task = @stuff.tasks
  end

  def new
    @task = Task.new
  end

  def create
  end

  def update
  end
  
  def destroy
  end

  def show
  end


  private
    def set_stuff
      @stuff = Stuff.find(params[:stuff_id])
    end

    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render "form", board: @board %>

<%= link_to "Show", board_path(@board) %> |
<%= link_to "Back", boards_path %>

app/views/boards/index.html.erb
<h1 class="ui header">Le Boards</h1>
<%= link_to 'New Board', new_board_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @boards.each do |board| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="column">
        <div class="ui inverted segment">
          <%= link_to "#{board.name}", board, class: "header" %>
        </div>
            <div class="extra content">
              <div class="ui two buttons">
            <div class="ui basic purple button inverted">
              <%= link_to 'Edit', edit_board_path(board) %>
            </div>
            <div class="ui basic red button inverted">
               <%= link_to "Destroy", board_path(board), method: :delete, data: { confirm: 'Do you really wanna delete me? ಥ_ಥ' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render "form", person: @board %>

<%= link_to "Back", boards_path %>

app/views/boards/show.html.erb
<div class="ui list">
  <div class="content">
    <p class="header">
      <%= @board.name %>
    </p>
  </div>
  <div class="extra content">
    <%= link_to 'View', board_stuffs_path(@board) %>
    <%= link_to 'Edit', edit_board_path(@board) %> |
    <%= link_to 'Back', boards_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inttroll</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/stuffs/_form.html.erb
<h1><%= @stuff.id ? 'Edit Stuff' : 'Create Stuff' %></h1>
<hr />
<%= form_for [@board, @stuff] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/stuffs/edit.html.erb
<h1>Stuffs#edit</h1>
<p>Find me in app/views/stuffs/edit.html.erb</p>

app/views/stuffs/index.html.erb
<h1>Choose Your Stuufffffs</h1>
<%= link_to 'Create Stuffff', new_board_stuff_path(@board) %>
<ul>
  <% @stuffs.each do |stuff| %>
    <li><%= link_to stuff.name, [@board, stuff] %></li>
  <% end %>
  <
  <%= link_to 'Go Back', board_path(@board) %>
</ul>

app/views/stuffs/new.html.erb
<h1>Stuffs#new</h1>
<p>Find me in app/views/stuffs/new.html.erb</p>

app/views/stuffs/show.html.erb
<h1><%= @board.name %> - <%= @stuff.name %></h1>
<p><%= @stuff.body %></p>
<%= link_to 'Edit Task', edit_board_stuff_path([@board, @stuff]) %>
<%= link_to 'Delete Task', [@board, @stuff], method: :delete %>
<%= link_to 'Back To Stuffs', board_stuffs_path(@board) %>

app/views/tasks/_task.html.erb
<hr />
<p>Author: <%= task.author %></p>
<p><strong><%= task.body %></strong></p>
</hr>

app/views/tasks/new.html.erb
<h1>Add Task</h1>
<%= form_for [@stuff, @task] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @board.name %> - <%= @stuff.name %></h1>
<p><%= @stuff.body %></p>
<h2>Task</h2>

<% @stuff.tasks.each do |task| %>
  <%= render 'tasks/task', { task: task } %>
<% end %>

<hr />
<%= link_to 'Edit Task', edit_board_stuff_path([@board, @stuff]) %>
<%= link_to 'Delete Task', [@board, @stuff], method: :delete %>
<%= link_to 'Return To Stuff', board_stuffs_path(@board) %>